/*
-- Query: SELECT * FROM apocalypse.survivor
LIMIT 0, 1000

-- Date: 2022-02-21 11:34
*/
USE apocalypse;
INSERT INTO `survivor` (`ID`,`AGE`,`GENDER`,`INFECTED`,`NAME`,`LATITUDE`,`LONGITUDE`) VALUES (201,30,0,0,'James Bond',104.5,134.7);
INSERT INTO `survivor` (`ID`,`AGE`,`GENDER`,`INFECTED`,`NAME`,`LATITUDE`,`LONGITUDE`) VALUES (202,25,1,0,'Jesica More',104.5,134.7);
INSERT INTO `survivor` (`ID`,`AGE`,`GENDER`,`INFECTED`,`NAME`,`LATITUDE`,`LONGITUDE`) VALUES (203,25,0,0,'Json Borne',205.5,122.8);
INSERT INTO `survivor` (`ID`,`AGE`,`GENDER`,`INFECTED`,`NAME`,`LATITUDE`,`LONGITUDE`) VALUES (204,30,1,1,'Mary Smith',305.5,122.8);
INSERT INTO `survivor` (`ID`,`AGE`,`GENDER`,`INFECTED`,`NAME`,`LATITUDE`,`LONGITUDE`) VALUES (205,40,0,0,'Adam Smith',305.5,122.8);
INSERT INTO `survivor` (`ID`,`AGE`,`GENDER`,`INFECTED`,`NAME`,`LATITUDE`,`LONGITUDE`) VALUES (206,40,0,0,'Aderson Neo',150.22,222.89);
INSERT INTO `survivor` (`ID`,`AGE`,`GENDER`,`INFECTED`,`NAME`,`LATITUDE`,`LONGITUDE`) VALUES (207,35,1,0,'Trinity Aderson',150.22,222.89);
INSERT INTO `survivor` (`ID`,`AGE`,`GENDER`,`INFECTED`,`NAME`,`LATITUDE`,`LONGITUDE`) VALUES (208,50,0,1,'Stone Steve',180.3,222.56);
INSERT INTO `survivor` (`ID`,`AGE`,`GENDER`,`INFECTED`,`NAME`,`LATITUDE`,`LONGITUDE`) VALUES (209,23,1,1,'John Terry',205.6,117.6);
INSERT INTO `survivor` (`ID`,`AGE`,`GENDER`,`INFECTED`,`NAME`,`LATITUDE`,`LONGITUDE`) VALUES (210,22,1,0,'Mary Jay',205.22,105.66);
INSERT INTO `survivor` (`ID`,`AGE`,`GENDER`,`INFECTED`,`NAME`,`LATITUDE`,`LONGITUDE`) VALUES (211,23,0,0,'Peter Packer',205.22,105.66);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('AMMUNITION',201);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('MEDICATION',201);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('WATER',201);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('AMUNITION',202);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('FOOD',202);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('AMMUNITION',203);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('MEDICATION',203);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('WATER',203);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('FOOD',204);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('MEDICATION',204);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('WATER',204);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('AMMUNITION',205);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('WATER',205);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('AMMUNITION',206);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('WATER',206);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('AMMUNITION',207);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('FOOD',207);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('MEDICATION',207);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('FOOD',208);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('WATER',208);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('FOOD',209);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('MEDICATION',209);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('FOOD',210);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('MEDICATION',210);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('WATER',210);
INSERT INTO `resource` (`TYPE`,`SURVIVOR_ID`) VALUES ('WATER',211);
